project_id: ethereal-yen-394407
database_region: europe-west1
database_instance_name: nationbuilder
database_user:
    user_name: SQL_user
    password: .:@u$8SeAL^"UHV+
    database_name: SwitchSkills