name: Deploy to Google APP Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'https://iam.googleapis.com/projects/760707122046/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'deploy-github-actions@ethereal-yen-394407.iam.gserviceaccount.com'

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.CREDENTIALS }}
